const getInitialCase = () => {
  return {
    id: "",
    complaint: "Non-Payment of Rent",
    createPropertyType: "",
    // property: {},
    propertyId: -1,
    buildingNo: null,
    tenantInfoCorrect: "",
    tenants: [],
    tenantsSaved: true,
    tenantType: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseTypeTitle: "",
    leaseTypeCategory: "",
    leaseStartDate: null,
    mileagePrice: 0,
    // mileageNeighborhood: "",
    // mileageAnswer: 0,
    signature: "",
    signatureImage: "",
    signatureImageBase64: "",
    signatureText: "",
    section8: "",
    rentCycle: "",
    rentDueBy: "",
    rentAmount: 0,
    section8Subsidy: 0,
    section8TenantPortion: 0,
    publicHousingOfficeSection8: null,
    pastDueRent: [],
    additionalChargesPermitted: null,
    lateCharges: [],
    utilities: [],
    fees: [],
    otherCharges: [],
    legalFeesPermitted: null,
    legalFees: "",
    feesTotal: 0,
    documentsUploadPermitted: null,
    documents: [],
    attorneyId: null,
    serviceId: null,
    filingPlan: "",
    confirmation: {},
    verification: {},
    rentDueBeforeTrial: "",
  };
};

export default getInitialCase;
